import type { AgentProvider } from "../agents/provider.js";import { assertTransition } from "./state-machine.js";import type { TaskStore } from "./store.js";import type { TaskEvent,TaskSpec } from "./types.js";import { WorkspaceManager } from "../infra/workspace.js";import { WorkspaceToolset } from "../tools/workspace.js";import { CompositeToolset,McpToolPlane } from "../tools/mcp.js";import { GitHubClient } from "../github/client.js";
export class Orchestrator{
 constructor(private store:TaskStore,private gpt:AgentProvider,private claude:AgentProvider,private workspaces=new WorkspaceManager(),private github?:GitHubClient,private maxTurns=Number(process.env.MAX_AGENT_TURNS||8)){}
 async run(taskId:string){const task=await this.store.getTask(taskId);if(!task)throw new Error("Task not found");const ws=await this.workspaces.create(task.id,task.repository,task.baseBranch);const writeTools=new WorkspaceToolset(ws.path,task.testCommand,true),readTools=new WorkspaceToolset(ws.path,task.testCommand,false);const mcp=new McpToolPlane(parseMcpServers());try{await mcp.initialize();}catch(e){await this.event(task.id,"MCP_INIT_FAILED","system",{error:String(e)});}const impl=new CompositeToolset([writeTools,mcp]),reviewTools=new CompositeToolset([readTools,mcp]);await this.patch(task.id,{branchName:ws.branch},"WORKSPACE_CREATED","system",{path:ws.path,branch:ws.branch});
try{await this.transition(task.id,"IMPLEMENTING");const plan=await this.gpt.run({agent:"gpt",taskId:task.id,workspacePath:ws.path,instruction:"Create an implementation plan for: "+task.objective+". Inspect the repository first.",context:await this.context(task.id,reviewTools)},reviewTools);await this.patch(task.id,{plan:plan.text},"GPT_PLAN","gpt",{text:plan.text,toolCalls:plan.toolCalls});const imp=await this.claude.run({agent:"claude",taskId:task.id,workspacePath:ws.path,instruction:"Implement the objective using this plan:\n"+plan.text,context:await this.context(task.id,impl)},impl);await this.event(task.id,"CLAUDE_IMPLEMENTATION","claude",{text:imp.text,toolCalls:imp.toolCalls});
for(let turn=0;turn<this.maxTurns;turn++){await this.transition(task.id,"TESTING");const testOutput=await impl.execute("run_tests",{});const ok=testOutput.startsWith("EXIT_CODE:0");await this.event(task.id,"TEST_RESULT","system",{ok,output:testOutput});await this.transition(task.id,"REVIEWING");const review=await this.gpt.run({agent:"gpt",taskId:task.id,workspacePath:ws.path,instruction:"Review the implementation. Return APPROVE if the objective and tests are satisfied; otherwise FIX with concrete findings. Test output:\n"+testOutput.slice(-12000),context:await this.context(task.id,reviewTools)},reviewTools);await this.patch(task.id,{latestReview:review.text},"GPT_REVIEW","gpt",{text:review.text,toolCalls:review.toolCalls});if(ok&&/^\s*APPROVE\b/i.test(review.text))break;if(turn===this.maxTurns-1)throw new Error("Agent iteration limit reached");await this.transition(task.id,"FIXING");const fix=await this.claude.run({agent:"claude",taskId:task.id,workspacePath:ws.path,instruction:"Fix the reviewer findings and test failures:\n"+review.text,context:await this.context(task.id,impl)},impl);await this.event(task.id,"CLAUDE_FIX","claude",{text:fix.text,toolCalls:fix.toolCalls});}
await this.transition(task.id,"OPEN_PR");const sha=await this.workspaces.commitAndPush(ws.path,ws.branch,"feat: implement ORCHESTRATOR task "+task.id);await this.event(task.id,"COMMITTED","system",{commitSha:sha});if(!this.github)throw new Error("GITHUB_TOKEN is required");const pr=await this.github.createPullRequest(task.repository,task.baseBranch,ws.branch,"ORCHESTRATOR: "+task.objective,"Opened by ORCHESTRATOR; awaiting human approval.");await this.patch(task.id,{pullRequestNumber:pr.number,pullRequestUrl:pr.url},"PR_OPENED","system",pr);await this.transition(task.id,"WAITING_HUMAN_APPROVAL");return (await this.store.getTask(task.id))!;}catch(e){const msg=String(e);const cur=await this.store.getTask(task.id);if(cur&&cur.state!=="FAILED"&&cur.state!=="COMPLETED"){try{await this.transition(task.id,"FAILED")}catch{}}await this.patch(task.id,{failureReason:msg},"TASK_FAILED","system",{error:msg});throw e;}}
 async approve(taskId:string){const task=await this.store.getTask(taskId);if(!task)throw new Error("Task not found");if(task.state!=="WAITING_HUMAN_APPROVAL"||!task.pullRequestNumber)throw new Error("Task is not awaiting approval");if(!this.github)throw new Error("GITHUB_TOKEN is required");await this.transition(taskId,"MERGING");await this.github.mergePullRequest(task.repository,task.pullRequestNumber);await this.transition(taskId,"COMPLETED");return (await this.store.getTask(taskId))!;}
 private async context(id:string,tools:AgentToolsLike){const events=await this.store.listEvents(id);return "Recent events:\n"+events.slice(-12).map(e=>e.type+" by "+e.actor+": "+JSON.stringify(e.payload).slice(0,1500)).join("\n")+"\nWorkspace:\n"+await tools.execute("git_status",{})+"\n"+await tools.execute("git_diff",{});}
 private async transition(id:string,state:TaskSpec["state"]){const t=await this.store.getTask(id);if(!t)throw new Error("Task not found");if(t.state===state)return;assertTransition(t.state,state);await this.store.updateTask(id,{state});await this.event(id,"STATE_CHANGED","system",{from:t.state,to:state});}
 private async event(id:string,type:string,actor:TaskEvent["actor"],payload:Record<string,unknown>){await this.store.appendEvent({taskId:id,type,actor,payload,createdAt:new Date().toISOString()});}
 private async patch(id:string,patch:Partial<TaskSpec>,type:string,actor:TaskEvent["actor"],payload:Record<string,unknown>){if(Object.keys(patch).length)await this.store.updateTask(id,patch);await this.event(id,type,actor,payload);}
}
type AgentToolsLike={execute(name:string,input:Record<string,unknown>):Promise<string>};
function parseMcpServers(){try{const v=JSON.parse(process.env.MCP_SERVERS_JSON||"[]");return Array.isArray(v)?v.filter((x:any)=>x&&typeof x.name==="string"&&typeof x.url==="string"):[];}catch{return [];}}